version: '2'

services:
      
  nodejs:
    container_name: nodejs
    build:
      context: nodejs/
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - './nodejs:/app'
      - '/app/node_modules'
    ports:
      - 3008:3008
    expose:
      - 3008
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql:5.7
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/:rw

volumes:
  my-db:

