version: '3'

services:
  react:
    container_name: react
    build:
      context: react/
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
    ports:
      - 80:80
    depends_on:
      - nodejs

  nodejs:
    container_name: nodejs
    build:
      context: nodejs/
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - './nodejs:/app'
      - '/app/node_modules'
    ports:
      - 4000:4000
    expose:
      - 4000
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:5.7
    container_name: mysql-service
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/:rw

volumes:
  my-db:

