version: '3.7'

services:

  react:
    container_name: react
    build:
      context: react/
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
      - '/app/node_modules'
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nodejs

  nodejs:
    container_name: nodejs
    build:
      context: nodejs/
      dockerfile: Dockerfile
    volumes:
      - './nodejs:/app'
      - '/app/node_modules'
    ports:
      - 3008:3008    
    
