version: '2'

services:

  react:
    container_name: react
    build:
      context: react/
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
      - '/app/node_modules'
    stdin_open: 
      true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - nodejs

  nodejs:
    container_name: nodejs
    build:
      context: nodejs/
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - './nodejs:/app'
      - '/app/node_modules'
    ports:
      - 3008:3008
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/:rw

volumes:
  my-db:
    
