apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer # Use NodePort for local development or ClusterIP if only internal access is needed