CREATE DATABASE IF NOT EXISTS mydb;

USE mydb;

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL
)  ENGINE=INNODB;

INSERT INTO tasks VALUES (1, 'get milk');

CREATE USER 'bob'@'%' IDENTIFIED BY 'passw###..9798AG';
GRANT ALL PRIVILEGES ON mydb.* TO 'bob'@'%';
FLUSH PRIVILEGES;